<?php
/**
 * @file
 * Control: Rotate.
 */

/**
 * Plugin definition.
 */
function openlayers_openlayers__control__rotate_openlayers_control() {
  return array(
    'handler' => array(
      'class' => 'openlayers__control__rotate',
      'file' => 'openlayers__control__rotate.inc',
    ),
  );
}

/**
 * Class openlayers__control__rotate.
 */
class openlayers__control__rotate extends openlayers_control {


}
