<?php
/**
 * @file
 * Control: ZoomSlider.
 */

/**
 * Plugin definition.
 */
function openlayers_openlayers__control__zoomslider_openlayers_control() {
  return array(
    'handler' => array(
      'class' => 'openlayers__control__zoomslider',
      'file' => 'openlayers__control__zoomslider.inc',
    ),
  );
}

/**
 * Class openlayers__control__zoomslider.
 */
class openlayers__control__zoomslider extends openlayers_control {


}
