<?php
/**
 * @file
 * Control: ScaleLine.
 */

/**
 * Plugin definition.
 */
function openlayers_openlayers__control__scaleline_openlayers_control() {
  return array(
    'handler' => array(
      'class' => 'openlayers__control__scaleline',
      'file' => 'openlayers__control__scaleline.inc',
    ),
  );
}

/**
 * Class openlayers__control__scaleline.
 */
class openlayers__control__scaleline extends openlayers_control {


}
