<?php
/**
 * @file
 * Control: ZoomExtent.
 */

/**
 * Plugin definition.
 */
function openlayers_openlayers__control__zoomtoextent_openlayers_control() {
  return array(
    'handler' => array(
      'class' => 'openlayers__control__zoomtoextent',
      'file' => 'openlayers__control__zoomtoextent.inc',
    ),
  );
}

/**
 * Class openlayers__control__zoomtoextent.
 */
class openlayers__control__zoomtoextent extends openlayers_control {


}
