<?php
/**
 * @file
 * Source: Vector.
 */

/**
 * Plugin definition.
 */
function openlayers_openlayers__source__vector_openlayers_source() {
  return array(
    'handler' => array(
      'class' => 'openlayers__source__vector',
      'file' => 'openlayers__source__vector.inc',
    ),
  );
}

/**
 * Class openlayers__source__vector.
 */
class openlayers__source__vector extends openlayers_source {

}
