<?php
/**
 * @file
 * Openlayers CDN main module file.
 */

/**
 * Implements hook_libraries_info().
 *
 * This hook will override the default 'openlayers3' library.
 * We don't use hook_libraries_info_alter() to avoid dealing with module's
 * weights.
 */
function openlayers_cdn_libraries_info() {
  $js_css_group = 'openlayers';
  if (class_exists('\Drupal\openlayers\Config')) {
    $js_css_group = \Drupal\openlayers\Config::get('openlayers.js_css.group');
  }

  $old_libraries = openlayers_libraries_info();

  $libraries['openlayers3'] = $old_libraries['openlayers3'];
  $libraries['openlayers3']['cdn'] = array(
    'aliases' => array('ol3', 'openlayers3'),
    'options' => array(
      'weight' => 0,
      'group' => $js_css_group,
    ),
  );

  return $libraries;
}
