<?php
/**
 * @file
 * Administrative UI for openlayers.
 */

/**
 * Implements hook_menu().
 */
function openlayers_ui_menu() {
  $items = array();

  // Core OpenLayers settings pages.
  $items['admin/structure/openlayers'] = array(
    'title' => 'Openlayers',
    'description' => 'Manage maps, layers, sources, controls, styles, and interactions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('openlayers_ui_admin_settings'),
    'access arguments' => array('administer openlayers'),
    'file' => 'includes/openlayers_ui.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/openlayers/settings'] = array(
    'title' => 'Settings',
    'access arguments' => array('administer openlayers'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 10,
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function openlayers_ui_ctools_plugin_directory($owner, $plugin_type) {
  return 'src/Plugin/' . $plugin_type;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function openlayers_ui_ctools_plugin_api($module, $api) {
  return array(
    'version' => 1,
    'path' => drupal_get_path('module', 'openlayers_ui') . '/includes'
  );
}

/**
 * Implements hook_help().
 */
function openlayers_ui_help($path, $arg) {
  $output = NULL;

  switch ($path) {
    case 'admin/help#openlayers':
      $output = '<p>' . t('Openlayers help') . '</p>';
      break;
    case 'admin/structure/openlayers':
      $output = '<p>' . t('Openlayers help') . '</p>';
      break;
    case 'admin/structure/openlayers/maps':
      $output = '<p>' . t('The map is the core component of OpenLayers.') . '</p>';
      break;
    case 'admin/structure/openlayers/projections':
      $output = '<p>' . t('Openlayers projection help') . '</p>';
      break;
    case 'admin/structure/openlayers/styles':
      $output = '<p>' . t('Openlayers style help') . '</p>';
      break;
    case 'admin/structure/openlayers/layers':
      $output = '<p>' . t('Openlayers layer help') . '</p>';
      break;
    case 'admin/structure/openlayers/sources':
      $output = '<p>' . t('Openlayers source help') . '</p>';
      break;
    case 'admin/structure/openlayers/controls':
      $output = '<p>' . t('Openlayers control help') . '</p>';
      break;
    case 'admin/structure/openlayers/interactions':
      $output = '<p>' . t('Openlayers interaction help') . '</p>';
      break;
    case 'admin/structure/openlayers/components':
      $output = '<p>' . t('Openlayers component help') . '</p>';
      break;
  }

  return $output;
}
