<?php
/**
 * @file
 * Class openlayers_control.
 */

namespace Drupal\openlayers;

/**
 * Class openlayers_control.
 */
abstract class Control extends Object implements ControlInterface {

  public function getType() {
    return 'control'; // TODO: Change the autogenerated stub
  }

}
